export const documentTypesData = [
  {
    key: 'aadhaar',
    label: 'Aadhaar Card',
    label_te: 'ఆధార్ కార్డు',
    label_hi: 'आधार कार्ड',
    where_to_get: 'UIDAI official portal (m-Aadhaar) or nearest Aadhaar Seva Kendra / MeeSeva / CSC',
  },
  {
    key: 'pan',
    label: 'PAN Card',
    label_te: 'పాన్ కార్డు',
    label_hi: 'पैन कार्ड',
    where_to_get: 'NSDL / UTIITSL portal or e-Filing Income Tax portal',
  },
  {
    key: 'income_certificate',
    label: 'Income Certificate',
    label_te: 'ఆదాయ ధ్రువీకరణ పత్రం',
    label_hi: 'आय प्रमाण पत्र',
    where_to_get: 'Tehsildar office / MeeSeva / CSC / State Citizen Service Portal',
  },
  {
    key: 'caste_certificate',
    label: 'Caste Certificate',
    label_te: 'కుల ధ్రువీకరణ పత్రం',
    label_hi: 'जाति प्रमाण पत्र',
    where_to_get: 'Revenue Department / MeeSeva / CSC / Tehsildar / Sub-Divisional Magistrate',
  },
  {
    key: 'residence_certificate',
    label: 'Residence / Domicile Certificate',
    label_te: 'నివాస ధ్రువీకరణ పత్రం',
    label_hi: 'निवास / अधिवास प्रमाण पत्र',
    where_to_get: 'Local Revenue Inspector / Tehsildar / MeeSeva / CSC',
  },
  {
    key: 'bank_passbook',
    label: 'Bank Account Passbook / Cancelled Cheque',
    label_te: 'బ్యాంక్ పాస్‌బుక్ / రద్దు చేసిన చెక్',
    label_hi: 'बैंक पासबुक / रद्द किया गया चेक',
    where_to_get: 'Any Nationalized / Commercial Bank or Post Office branch',
  },
  {
    key: 'land_records',
    label: 'Land Records (Pattadar Passbook / RoR 1B / Khasra)',
    label_te: 'భూమి పట్టాదారు పాస్‌బుక్ / రికార్డ్స్ (RoR 1B)',
    label_hi: 'भूमि रिकॉर्ड (खसरा-खतौनी / पट्टा पासबुक)',
    where_to_get: 'Dharani Portal / Bhulekh Portal / Revenue Divisional Office / Village Revenue Officer',
  },
  {
    key: 'ration_card',
    label: 'Ration Card (NFSA / Food Security Card)',
    label_te: 'రేషన్ కార్డు / ఆహార భద్రత కార్డు',
    label_hi: 'राशन कार्ड / खाद्य सुरक्षा कार्ड',
    where_to_get: 'Civil Supplies Department / MeeSeva / CSC / PDS Office',
  },
  {
    key: 'passport_photo',
    label: 'Passport Size Photographs',
    label_te: 'పాస్‌పోర్ట్ సైజు ఫోటోలు',
    label_hi: 'पासपोर्ट आकार की तस्वीरें',
    where_to_get: 'Any local photo studio or self-captured print',
  },
  {
    key: 'age_proof',
    label: 'Age Proof (Birth Certificate / SSC Marks Memo)',
    label_te: 'వయస్సు ధ్రువీకరణ పత్రం',
    label_hi: 'आयु प्रमाण पत्र (जन्म प्रमाण पत्र / अंकतालिका)',
    where_to_get: 'Municipal Corporation / Gram Panchayat / School Education Board',
  },
  {
    key: 'education_certificates',
    label: 'Educational Certificates & Marksheets',
    label_te: 'విద్యా అర్హత సర్టిఫికెట్లు',
    label_hi: 'शैक्षिक प्रमाण पत्र एवं अंकतालिका',
    where_to_get: 'Issued by School / University / Recognized Board',
  },
  {
    key: 'business_proof',
    label: 'Business Proof (Udyam MSME / Trade License / Vending ID)',
    label_te: 'వ్యాపార గుర్తింపు పత్రం (ఉద్యమ్ / లైసెన్స్)',
    label_hi: 'व्यवसाय प्रमाण (उद्यम पंजीकरण / ट्रेड लाइसेंस)',
    where_to_get: 'Udyam Registration portal (udyamregistration.gov.in) or Local Urban Body',
  },
  {
    key: 'bpl_card',
    label: 'BPL Card / Antyodaya Anna Yojana (AAY) Card',
    label_te: 'దారిద్య్రరేఖకు దిగువన (BPL) కార్డు',
    label_hi: 'बीपीएल राशन कार्ड / अंत्योदय कार्ड',
    where_to_get: 'District Food & Civil Supplies Department',
  },
  {
    key: 'disability_certificate',
    label: 'Disability Certificate / UDID Card',
    label_te: 'వికలాంగుల ధ్రువీకరణ పత్రం (UDID)',
    label_hi: 'दिव्यांगता प्रमाण पत्र / यूडीआईडी कार्ड',
    where_to_get: 'District Hospital Medical Board / Swavlamban Card portal',
  },
  {
    key: 'marriage_certificate',
    label: 'Marriage Certificate',
    label_te: 'వివాహ రిజిస్ట్రేషన్ సర్టిఫికెట్',
    label_hi: 'विवाह प्रमाण पत्र',
    where_to_get: 'Sub-Registrar Office / Municipal Corporation / Village Panchayat',
  },
  {
    key: 'birth_certificate',
    label: 'Child Birth Certificate',
    label_te: 'జనన ధ్రువీకరణ పత్రం',
    label_hi: 'जन्म प्रमाण पत्र',
    where_to_get: 'Civil Registration System (CRS) / Municipal Authority / Hospital',
  },
];

export const schemesData = [
  {
    slug: 'pm-kisan',
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    name_te: 'ప్రధాన మంత్రి కిసాన్ సమ్మాన్ నిధి (పీఎం-కిసాన్)',
    name_hi: 'प्रधानमंत्री किसान सम्मान निधि (पीएम-किसान)',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    level: 'central',
    state: null,
    category: 'agriculture',
    benefit_summary: 'Direct income support of ₹6,000 per year transferred in 3 equal four-monthly installments of ₹2,000 directly into the bank accounts of land-holding farmer families.',
    eligibility_summary: 'All land-holding farmer families having cultivable landholding in their names. Institutional landholders and high-income taxpayers excluded.',
    required_doc_keys: ['aadhaar', 'land_records', 'bank_passbook', 'passport_photo'],
    application_steps: [
      { title: 'Farmer Registration', detail: 'Visit pmkisan.gov.in and click "New Farmer Registration" or visit nearest CSC/MeeSeva centre.' },
      { title: 'Enter Aadhaar & Mobile', detail: 'Authenticate your Aadhaar number and OTP received on registered mobile.' },
      { title: 'Fill Land Details', detail: 'Enter state, district, sub-district, village, and survey/khata land numbers matching your land records.' },
      { title: 'Upload Documents & e-KYC', detail: 'Upload landholding passbook copy and bank details. Complete biometric or OTP based e-KYC.' },
      { title: 'Verification by State Nodal Officer', detail: 'State Revenue Department verifies revenue records before fund disbursement.' }
    ],
    official_url: 'https://pmkisan.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-fasal-bima-yojana',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    name_te: 'ప్రధాన మంత్రి ఫసల్ బీమా యోజన',
    name_hi: 'प्रधानमंत्री फसल बीमा योजना',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    level: 'central',
    state: null,
    category: 'agriculture',
    benefit_summary: 'Comprehensive crop insurance covering non-preventable natural risks from pre-sowing to post-harvest with lowest farmer premiums (1.5% to 2% for food crops, 5% for commercial/horticultural).',
    eligibility_summary: 'All farmers growing notified crops in notified areas including sharecroppers and tenant farmers.',
    required_doc_keys: ['aadhaar', 'land_records', 'bank_passbook', 'residence_certificate'],
    application_steps: [
      { title: 'Check Crop Cut-off Date', detail: 'Verify crop insurance cut-off dates for the Kharif or Rabi season on pmfby.gov.in.' },
      { title: 'Apply at Bank or Portal', detail: 'Apply via designated bank branch, CSC centre, or directly through the PMFBY portal.' },
      { title: 'Submit Sowing Certificate', detail: 'Submit land possession certificate and sowing certificate issued by village officer.' },
      { title: 'Pay Subsidized Premium', detail: 'Pay the minimal premium share; balance is funded equally by Central & State governments.' }
    ],
    official_url: 'https://pmfby.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'kisan-credit-card',
    name: 'Kisan Credit Card (KCC) Scheme',
    name_te: 'కిసాన్ క్రెడిట్ కార్డ్ పథకం',
    name_hi: 'किसान क्रेडिट कार्ड (केसीसी)',
    ministry: 'Ministry of Finance / Agriculture',
    level: 'central',
    state: null,
    category: 'finance',
    benefit_summary: 'Concessional institutional credit up to ₹3 Lakh at an effective interest rate of 4% per annum (with prompt repayment incentive) for agricultural inputs, machinery, and allied activities.',
    eligibility_summary: 'All farmers, individual or joint borrowers, tenant farmers, oral lessees, sharecroppers, and SHGs of farmers.',
    required_doc_keys: ['aadhaar', 'pan', 'land_records', 'bank_passbook', 'passport_photo'],
    application_steps: [
      { title: 'Download One-Page Form', detail: 'Obtain the simplified KCC application form from bank branch or pmkisan.gov.in.' },
      { title: 'Attach Land & Sowing Details', detail: 'Attach copies of land title deeds, cropping pattern details, and Aadhaar card.' },
      { title: 'Bank Branch Appraisal', detail: 'Submit to your commercial bank, regional rural bank (RRB), or cooperative bank.' },
      { title: 'Card Issuance', detail: 'Bank issues RuPay KCC card with pre-sanctioned revolving credit limit within 14 days.' }
    ],
    official_url: 'https://myscheme.gov.in/schemes/kcc',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'rythu-bandhu',
    name: 'Rythu Bandhu (Telangana Farmer Investment Support)',
    name_te: 'రైతు బంధు పథకం (తెలంగాణ)',
    name_hi: 'रैतु बंधु योजना (तेलंगाना)',
    ministry: 'Department of Agriculture, Govt. of Telangana',
    level: 'state',
    state: 'Telangana',
    category: 'agriculture',
    benefit_summary: 'Investment support of ₹5,000 per acre per season (₹10,000 per acre annually) to support purchase of seeds, fertilizers, pesticides, and field preparations.',
    eligibility_summary: 'Resident farmers of Telangana holding Pattadar passbooks with land titles recorded on Dharani portal.',
    required_doc_keys: ['aadhaar', 'land_records', 'bank_passbook', 'residence_certificate'],
    application_steps: [
      { title: 'Verify Dharani RoR', detail: 'Ensure your land holding is updated and verified on the Dharani integrated land portal.' },
      { title: 'Submit Bank Account to AEO', detail: 'Provide Aadhaar-seeded bank account to your village Agricultural Extension Officer (AEO).' },
      { title: 'Direct Benefit Transfer', detail: 'Amount gets directly deposited through DBT during Kharif and Rabi cycles.' }
    ],
    official_url: 'https://rythubandhu.telangana.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-awas-yojana',
    name: 'Pradhan Mantri Awas Yojana (PMAY-G / PMAY-U)',
    name_te: 'ప్రధాన మంత్రి ఆవాస్ యోజన',
    name_hi: 'प्रधानमंत्री आवास योजना',
    ministry: 'Ministry of Housing and Urban Affairs / Ministry of Rural Development',
    level: 'central',
    state: null,
    category: 'housing',
    benefit_summary: 'Financial assistance of ₹1.20 Lakh in plains and ₹1.30 Lakh in hilly/difficult areas for pucca house construction, plus interest subsidies up to 6.5% for urban beneficiaries.',
    eligibility_summary: 'Houseless families or families living in zero, one, or two-room kutcha houses as per SECC census, BPL households, and EWS/LIG income brackets.',
    required_doc_keys: ['aadhaar', 'income_certificate', 'bank_passbook', 'bpl_card', 'residence_certificate', 'passport_photo'],
    application_steps: [
      { title: 'Gram Sabha / Urban Portal Check', detail: 'Verify name in PMAY Permanent Wait List (PWL) at Gram Panchayat or apply at pmaymis.gov.in.' },
      { title: 'Geo-Tagging Existing Site', detail: 'Government official inspects and geo-tags the existing kutcha house or proposed vacant plot.' },
      { title: 'Sanction Order', detail: 'District authorities issue the official house sanction letter.' },
      { title: 'Milestone Disbursals', detail: 'Funds credited in 3 to 4 stages linked to geotagged foundation, lintel, and roof completion.' }
    ],
    official_url: 'https://pmaymis.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'ayushman-bharat-pmjay',
    name: 'Ayushman Bharat PM-JAY',
    name_te: 'ఆయుష్మాన్ భారత్ పీఎం-జై',
    name_hi: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना',
    ministry: 'National Health Authority / Ministry of Health and Family Welfare',
    level: 'central',
    state: null,
    category: 'health',
    benefit_summary: 'Cashless health cover up to ₹5,00,000 per family per year for secondary and tertiary care hospitalization across empaneled public and private hospitals nationwide.',
    eligibility_summary: 'Deprived rural families and identified occupational categories of urban workers based on SECC 2011 database. No cap on family size or age.',
    required_doc_keys: ['aadhaar', 'ration_card', 'bpl_card'],
    application_steps: [
      { title: 'Check Eligibility', detail: 'Visit beneficiary.nha.gov.in or call 14555 to verify family name in the PM-JAY database.' },
      { title: 'Complete e-KYC', detail: 'Use Aadhaar OTP or visit nearest Ayushman Mitra desk at any empaneled hospital / CSC.' },
      { title: 'Download Ayushman PVC Card', detail: 'Download and print the Golden Ayushman Card featuring your unique ABHA ID.' },
      { title: 'Cashless Treatment', detail: 'Present Ayushman card at any empaneled hospital for 100% cashless hospitalization.' }
    ],
    official_url: 'https://pmjay.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'aarogyasri',
    name: 'Dr. YSR Aarogyasri / Telangana Aarogyasri',
    name_te: 'డాక్టర్ వైఎస్ఆర్ / తెలంగాణ ఆరోగ్యశ్రీ పథకం',
    name_hi: 'आरोग्यश्री स्वास्थ्य बीमा योजना',
    ministry: 'State Department of Health and Family Welfare (AP / Telangana)',
    level: 'state',
    state: 'Telangana',
    category: 'health',
    benefit_summary: 'Comprehensive cashless medical treatment coverage up to ₹5,00,000 (up to ₹10,00,000 in AP) for critical ailments and recognized surgical procedures.',
    eligibility_summary: 'Families holding state White Ration Card / Food Security Card with annual family income below ₹5,00,000.',
    required_doc_keys: ['aadhaar', 'ration_card', 'residence_certificate', 'income_certificate'],
    application_steps: [
      { title: 'Obtain Food Security Card', detail: 'Ensure your family is enlisted on an active state White Food Security / BPL Ration Card.' },
      { title: 'Visit Network Hospital', detail: 'Report to the Aarogyasri Help Desk (Aarogya Mithra) at any recognized network hospital.' },
      { title: 'Pre-Authorization', detail: 'Hospital doctors upload case diagnosis and get digital approval from the Aarogyasri Trust.' },
      { title: 'Treatment & Free Medicines', detail: 'Receive fully cashless surgery, post-operative care, and free medicines for 30 days.' }
    ],
    official_url: 'https://aarogyasri.telangana.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'sukanya-samriddhi-yojana',
    name: 'Sukanya Samriddhi Yojana (SSY)',
    name_te: 'సుకున్య సమృద్ధి యోజన',
    name_hi: 'सुकन्या समृद्धि योजना',
    ministry: 'Ministry of Finance / Women and Child Development',
    level: 'central',
    state: null,
    category: 'women_child',
    benefit_summary: 'High interest rate small savings scheme (currently 8.2% p.a.) with triple tax exemption (EEE) under Section 80C for the higher education and marriage of a girl child.',
    eligibility_summary: 'Parent or legal guardian of a girl child aged 10 years or below. Maximum 2 accounts per family (or 3 in case of twin girls).',
    required_doc_keys: ['birth_certificate', 'aadhaar', 'pan', 'passport_photo', 'residence_certificate'],
    application_steps: [
      { title: 'Collect Account Opening Form', detail: 'Obtain Form-1 from any Post Office or authorized commercial bank branch.' },
      { title: 'Submit Child Birth Certificate', detail: 'Enclose verified birth certificate of the girl child and KYC documents of guardian.' },
      { title: 'Initial Deposit', detail: 'Make an initial deposit of at least ₹250 (max ₹1.5 Lakh per financial year).' },
      { title: 'Passbook Issuance', detail: 'Post office or bank issues the SSY passbook to track contributions and accrued interest.' }
    ],
    official_url: 'https://www.indiapost.gov.in/Financial/Pages/Content/Sukanya-Samriddhi-Account.aspx',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-mudra-yojana',
    name: 'Pradhan Mantri MUDRA Yojana (PMMY)',
    name_te: 'ప్రధాన మంత్రి ముద్ర యోజన',
    name_hi: 'प्रधानमंत्री मुद्रा योजना',
    ministry: 'Ministry of Finance',
    level: 'central',
    state: null,
    category: 'finance',
    benefit_summary: 'Collateral-free business loans up to ₹20 Lakh across Shishu (up to ₹50,000), Kishore (₹50k-₹5Lakh), and Tarun (₹5Lakh-₹20Lakh) categories for small businesses.',
    eligibility_summary: 'Any non-farm, non-corporate micro/small entrepreneur engaged in manufacturing, trading, or services.',
    required_doc_keys: ['aadhaar', 'pan', 'business_proof', 'bank_passbook', 'residence_certificate', 'passport_photo'],
    application_steps: [
      { title: 'Prepare Business Plan', detail: 'Draft project report indicating capital equipment costs, working capital, and projected revenue.' },
      { title: 'Apply via Udyamimitra', detail: 'Submit application online at udyamimitra.in or visit any commercial / rural bank.' },
      { title: 'KYC & Loan Appraisal', detail: 'Bank branch conducts field appraisal without asking for collateral security.' },
      { title: 'Sanction & MUDRA Card', detail: 'Loan is sanctioned and MUDRA debit card is issued for revolving working capital withdrawal.' }
    ],
    official_url: 'https://www.mudra.org.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'stand-up-india',
    name: 'Stand-Up India Scheme',
    name_te: 'స్టాండప్ ఇండియా పథకం',
    name_hi: 'स्टैंड-अप इंडिया योजना',
    ministry: 'Ministry of Finance',
    level: 'central',
    state: null,
    category: 'finance',
    benefit_summary: 'Bank loans between ₹10 Lakh and ₹1 Crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch.',
    eligibility_summary: 'SC/ST and/or women entrepreneurs above 18 years of age setting up greenfield enterprises in manufacturing, services, or trading sectors.',
    required_doc_keys: ['aadhaar', 'pan', 'caste_certificate', 'business_proof', 'bank_passbook', 'residence_certificate', 'passport_photo'],
    application_steps: [
      { title: 'Register on Stand-Up India Portal', detail: 'Register at standupmitra.in and complete borrower profile assessment.' },
      { title: 'Select Lending Bank', detail: 'Select preferred public or private sector commercial bank branch for greenfield setup.' },
      { title: 'Submit Project Feasibility Report', detail: 'Provide DPR (Detailed Project Report) with margin money (min 15%) confirmation.' },
      { title: 'Sanction & Credit Guarantee', detail: 'Loan sanctioned backed by National Credit Guarantee Trustee Company (NCGTC).' }
    ],
    official_url: 'https://www.standupmitra.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-svanidhi',
    name: 'PM Street Vendor\'s AtmaNirbhar Nidhi (PM SVANidhi)',
    name_te: 'పీఎం స్వనిధి (వీధి వ్యాపారుల ఆత్మనిర్భర్ నిధి)',
    name_hi: 'पीएम स्वनिधि (स्ट्रीट वेंडर्स आत्मनिर्भर निधि)',
    ministry: 'Ministry of Housing and Urban Affairs',
    level: 'central',
    state: null,
    category: 'employment',
    benefit_summary: 'Affordable working capital loan starting at ₹10,000 (1st tranche), ₹20,000 (2nd tranche), and up to ₹50,000 (3rd tranche) with 7% interest subsidy and cashback on digital transactions.',
    eligibility_summary: 'Street vendors and hawkers vending in urban areas on or before March 24, 2020 holding a Certificate of Vending or Letter of Recommendation (LoR).',
    required_doc_keys: ['aadhaar', 'bank_passbook', 'business_proof', 'passport_photo'],
    application_steps: [
      { title: 'Obtain Vending ID / LoR', detail: 'Collect Certificate of Vending from your Urban Local Body (Municipality) or apply for Letter of Recommendation.' },
      { title: 'Apply on pmsvanidhi Portal', detail: 'Login to pmsvanidhi.mohua.gov.in using Aadhaar-linked mobile OTP.' },
      { title: 'Select Preferred Lending Institution', detail: 'Choose your nearby bank or microfinance institution.' },
      { title: 'Direct Disbursal', detail: 'Loan amount is directly disbursed into your bank account within 10 days.' }
    ],
    official_url: 'https://pmsvanidhi.mohua.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-vishwakarma',
    name: 'PM Vishwakarma Scheme',
    name_te: 'పీఎం విశ్వకర్మ పథకం',
    name_hi: 'पीएम विश्वकर्मा योजना',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    level: 'central',
    state: null,
    category: 'employment',
    benefit_summary: 'Recognition as Vishwakarma with ID card, skill verification with ₹500/day stipend, toolkit incentive of ₹15,000, and collateral-free enterprise credit up to ₹3 Lakh at concessional 5% interest.',
    eligibility_summary: 'Traditional artisans and craftspeople working with hands and tools in 18 identified trades (carpenters, blacksmiths, potters, cobblers, tailors, weavers, etc.). Min age 18.',
    required_doc_keys: ['aadhaar', 'bank_passbook', 'business_proof', 'residence_certificate', 'passport_photo'],
    application_steps: [
      { title: 'Register at CSC Centre', detail: 'Visit nearest Common Service Centre with Aadhaar and active bank account passbook.' },
      { title: 'Select Traditional Trade', detail: 'Register under one of the 18 traditional family craft trades.' },
      { title: 'Gram Panchayat & District Verification', detail: 'Application is verified by Village Sarpanch / Executive Officer and District Committee.' },
      { title: 'Training & Toolkit Voucher', detail: 'Attend 5-7 days basic skill training, receive ₹15,000 digital e-voucher for toolkit.' }
    ],
    official_url: 'https://pmvishwakarma.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'mgnrega',
    name: 'Mahatma Gandhi NREGA',
    name_te: 'మహాత్మా గాంధీ జాతీయ గ్రామీణ ఉపాధి హామీ పథకం',
    name_hi: 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम',
    ministry: 'Ministry of Rural Development',
    level: 'central',
    state: null,
    category: 'employment',
    benefit_summary: 'Legal guarantee of 100 days of wage employment per financial year to adult members of any rural household willing to do public work-related unskilled manual labor.',
    eligibility_summary: 'All adult members of rural households willing to do unskilled manual work. Must be an Indian citizen residing in rural panchayat.',
    required_doc_keys: ['aadhaar', 'bank_passbook', 'residence_certificate', 'passport_photo'],
    application_steps: [
      { title: 'Apply for Job Card', detail: 'Submit plain paper application or oral request to Gram Panchayat with family photos and Aadhaar.' },
      { title: 'Job Card Issuance', detail: 'Panchayat issues MGNREGA Job Card containing household member details within 15 days.' },
      { title: 'Demand Work', detail: 'Submit dated written application demanding employment for at least 14 continuous days.' },
      { title: 'Direct Wage Deposit', detail: 'Wages directly transferred into Aadhaar-linked bank/post office account within 15 days of work muster.' }
    ],
    official_url: 'https://nrega.nic.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-ujjwala-yojana',
    name: 'Pradhan Mantri Ujjwala Yojana (PMUY 2.0)',
    name_te: 'ప్రధాన మంత్రి ఉజ్జ్వల యోజన',
    name_hi: 'प्रधानमंत्री उज्ज्वला योजना 2.0',
    ministry: 'Ministry of Petroleum and Natural Gas',
    level: 'central',
    state: null,
    category: 'women_child',
    benefit_summary: 'Deposit-free LPG connection including free first cylinder and hotplate/stove, plus targeted subsidy of ₹300 per 14.2 kg cylinder for up to 12 refills per year.',
    eligibility_summary: 'Adult woman from poor/BPL household having no existing LPG connection in the family. Includes SC/ST, PMAY beneficiaries, and Antyodaya households.',
    required_doc_keys: ['aadhaar', 'ration_card', 'bank_passbook', 'bpl_card', 'passport_photo'],
    application_steps: [
      { title: 'Apply Online or at LPG Distributor', detail: 'Visit nearest Indane, Bharat Gas, or HP Gas distributor, or apply at pmuy.gov.in.' },
      { title: 'Submit Family Declaration', detail: 'Submit 14-point declaration certifying that no other family member possesses an LPG connection.' },
      { title: 'Aadhaar e-KYC', detail: 'Complete biometric or OTP-based e-KYC for the female head of the household.' },
      { title: 'LPG Kit Handover', detail: 'Receive free regulator, hose pipe, stove, and filled 14.2kg LPG cylinder.' }
    ],
    official_url: 'https://www.pmuy.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'atal-pension-yojana',
    name: 'Atal Pension Yojana (APY)',
    name_te: 'అటల్ పెన్షన్ యోజన',
    name_hi: 'अटल पेंशन योजना',
    ministry: 'Pension Fund Regulatory and Development Authority (PFRDA) / Ministry of Finance',
    level: 'central',
    state: null,
    category: 'social_security',
    benefit_summary: 'Guaranteed monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000, or ₹5,000 per month starting from age 60 until death, with full corpus returned to nominee.',
    eligibility_summary: 'Indian citizens aged between 18 and 40 years holding a savings bank account. Must not be an income taxpayer.',
    required_doc_keys: ['aadhaar', 'bank_passbook', 'passport_photo'],
    application_steps: [
      { title: 'Visit Savings Bank Branch', detail: 'Approach the bank branch or post office where you maintain your savings account.' },
      { title: 'Fill APY Subscriber Registration', detail: 'Choose your desired monthly pension amount (₹1,000 to ₹5,000) and specify nominee details.' },
      { title: 'Auto-Debit Authorization', detail: 'Provide auto-debit consent for monthly/quarterly contribution based on your entry age.' },
      { title: 'Obtain PRAN Card', detail: 'Download APY Permanent Retirement Account Number (PRAN) e-card from NSDL portal.' }
    ],
    official_url: 'https://www.npscra.nsdl.co.in/scheme-details.php',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-jeevan-jyoti-bima',
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    name_te: 'ప్రధాన మంత్రి జీవన్ జ్యోతి బీమా యోజన',
    name_hi: 'प्रधानमंत्री जीवन ज्योति बीमा योजना',
    ministry: 'Ministry of Finance',
    level: 'central',
    state: null,
    category: 'social_security',
    benefit_summary: 'Life insurance cover of ₹2,00,000 in case of death of the insured due to any cause at a modest annual premium of ₹436 auto-debited from bank account.',
    eligibility_summary: 'Individuals aged 18 to 50 years holding an active bank or post office savings account who give consent for auto-debit.',
    required_doc_keys: ['aadhaar', 'bank_passbook'],
    application_steps: [
      { title: 'Submit Consent-cum-Declaration', detail: 'Login to netbanking/mobile banking or submit simple enrollment form at bank branch.' },
      { title: 'Nominee Details', detail: 'Name nominee (spouse, children, or parent) and their relationship.' },
      { title: 'Auto-Debit Activation', detail: 'Maintain sufficient balance in May for annual auto-debit of ₹436.' },
      { title: 'Policy Confirmation Slip', detail: 'Collect acknowledgement slip or digital certificate of insurance.' }
    ],
    official_url: 'https://financialservices.gov.in/beta/en/pmjjby',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'pm-suraksha-bima',
    name: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    name_te: 'ప్రధాన మంత్రి సురక్షా బీమా యోజన',
    name_hi: 'प्रधानमंत्री सुरक्षा बीमा योजना',
    ministry: 'Ministry of Finance',
    level: 'central',
    state: null,
    category: 'social_security',
    benefit_summary: 'Accidental death and total permanent disability cover of ₹2,00,000 (and ₹1,00,000 for partial permanent disability) for just ₹20 per year.',
    eligibility_summary: 'All citizens aged 18 to 70 years holding a savings bank account with auto-debit facility enabled.',
    required_doc_keys: ['aadhaar', 'bank_passbook'],
    application_steps: [
      { title: 'Enable Auto-Debit', detail: 'Opt-in via your bank netbanking app, SMS, or fill form at your bank branch.' },
      { title: 'Assign Nominee', detail: 'Provide nominee details and KYC.' },
      { title: 'Annual Renewal', detail: '₹20 is automatically deducted every year between May 25 and May 31.' },
      { title: 'Claim Form Availability', detail: 'In unfortunate accident, nominee submits FIR and death certificate to bank within 30 days.' }
    ],
    official_url: 'https://financialservices.gov.in/beta/en/pmsby',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'national-scholarship-portal',
    name: 'Post-Matric Scholarship Scheme (National Scholarship Portal)',
    name_te: 'పోస్ట్-మెట్రిక్ స్కాలర్‌షిప్ పథకం (నేషనల్ స్కాలర్‌షిప్ పోర్టల్)',
    name_hi: 'पोस्ट-मैट्रिक छात्रवृत्ति योजना (राष्ट्रीय छात्रवृत्ति पोर्टल)',
    ministry: 'Ministry of Social Justice and Empowerment / Tribal Affairs / Minority Affairs',
    level: 'central',
    state: null,
    category: 'education',
    benefit_summary: '100% tuition fee reimbursement and maintenance allowance ranging from ₹2,500 to ₹13,500 per year for students studying in class 11, 12, ITI, Diploma, Graduation, and Post-Graduation.',
    eligibility_summary: 'Students belonging to SC, ST, OBC, EBC, or Minority communities pursuing recognized post-matric courses with family annual income under ₹2.5 Lakh.',
    required_doc_keys: ['aadhaar', 'income_certificate', 'caste_certificate', 'education_certificates', 'bank_passbook', 'residence_certificate', 'passport_photo'],
    application_steps: [
      { title: 'Register with OTR on NSP', detail: 'Generate One-Time Registration (OTR) on scholarships.gov.in with Aadhaar verification.' },
      { title: 'Fill Academic Details', detail: 'Enter current institute code, roll number, course name, and previous year marks.' },
      { title: 'Upload Certificates', detail: 'Upload scanned copies of caste, income, bonafide student certificate, and marks sheets.' },
      { title: 'Institute Verification', detail: 'Institute Nodal Officer (INO) and District Officer (DNO) digitally verify before DBT disbursement.' }
    ],
    official_url: 'https://scholarships.gov.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'janani-suraksha-yojana',
    name: 'Janani Suraksha Yojana (JSY)',
    name_te: 'జననీ సురక్ష యోజన',
    name_hi: 'जननी सुरक्षा योजना',
    ministry: 'Ministry of Health and Family Welfare',
    level: 'central',
    state: null,
    category: 'women_child',
    benefit_summary: 'Direct cash assistance of ₹1,400 (rural) or ₹1,000 (urban) to pregnant mothers delivering in institutional healthcare facilities, plus ₹300-₹600 ASHA incentive.',
    eligibility_summary: 'All pregnant women delivering in government health centers or accredited private hospitals. In high-performing states, limited to BPL/SC/ST mothers aged 19+.',
    required_doc_keys: ['aadhaar', 'bpl_card', 'bank_passbook', 'residence_certificate', 'birth_certificate'],
    application_steps: [
      { title: 'Early ANC Registration', detail: 'Register pregnancy within first trimester at nearest Sub-Center or Primary Health Center (PHC).' },
      { title: 'Get MCP Card', detail: 'Obtain Mother and Child Protection (MCP) card and complete at least 3 Ante-Natal Checkups.' },
      { title: 'Institutional Delivery', detail: 'Deliver at a government hospital or accredited private health center.' },
      { title: 'Discharge Cash Transfer', detail: 'Cash assistance paid directly into mother\'s bank account prior to hospital discharge.' }
    ],
    official_url: 'https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309',
    last_verified: new Date().toISOString().split('T')[0],
  },
  {
    slug: 'nsap-old-age-pension',
    name: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS - NSAP)',
    name_te: 'జాతీయ వృద్ధాప్య పింఛను పథకం (ఇందిరా గాంధీ ఎన్ఎస్ఏపీ)',
    name_hi: 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना (एनएसएपी)',
    ministry: 'Ministry of Rural Development',
    level: 'central',
    state: null,
    category: 'social_security',
    benefit_summary: 'Monthly pension of ₹1,000 to ₹3,000 (Central component plus State top-up) for elderly citizens living below the poverty line.',
    eligibility_summary: 'Citizens aged 60 years or above belonging to a household living below the poverty line (BPL) as verified by local authorities.',
    required_doc_keys: ['aadhaar', 'age_proof', 'bpl_card', 'income_certificate', 'bank_passbook', 'passport_photo'],
    application_steps: [
      { title: 'Collect Form from Gram Panchayat / Ward', detail: 'Collect NSAP application form from local Village Panchayat office or Municipal Ward office.' },
      { title: 'Submit Age & BPL Proof', detail: 'Attach Aadhaar, electoral photo ID or school leaving certificate for age proof alongside BPL ration card.' },
      { title: 'Social Audit & Sanction', detail: 'Panchayat Gram Sabha verifies beneficiary status and forwards to Sub-Divisional Officer for sanction.' },
      { title: 'Monthly DBT Disbursement', detail: 'Pension credited directly on the 1st of every month to your bank/post office account.' }
    ],
    official_url: 'https://nsap.nic.in',
    last_verified: new Date().toISOString().split('T')[0],
  },
];

export const demoUserData = {
  email: 'demo@policypal.app',
  password: 'Demo@12345',
  full_name: 'Ramesh Patel',
  preferred_language: 'en',
  profile: {
    age: 42,
    gender: 'male',
    state: 'Telangana',
    district: 'Rangareddy',
    occupation: 'Small Farmer & Dairy Producer',
    annual_income: 180000,
    social_category: 'OBC',
    land_holding_acres: 2.5,
    education_level: 'High School (10th Pass)',
    is_student: false,
    is_farmer: true,
    is_business_owner: false,
    family_size: 4,
    notes: 'Family consists of wife and two school-going children. Owns 2.5 acres of agricultural land and 2 cows.',
  },
  // Initial user documents for demo
  documents: [
    { doc_key: 'aadhaar', is_ready: true, notes: 'Original card and linked mobile number active' },
    { doc_key: 'bank_passbook', is_ready: true, notes: 'State Bank of India account passbook updated' },
    { doc_key: 'land_records', is_ready: true, notes: 'Dharani Pattadar passbook available' },
    { doc_key: 'passport_photo', is_ready: true, notes: '4 copies available' },
  ],
  sampleAssessment: {
    situation_text: 'I am a 42-year-old small farmer living in Rangareddy, Telangana. I have 2.5 acres of dry land where I cultivate cotton and maize. My annual family income is around ₹1.8 Lakhs. My family consists of 4 members including two school-going children. I want financial support for farming inputs and affordable health coverage for my family.',
    language: 'en',
    extracted_profile: {
      age: 42,
      gender: 'male',
      state: 'Telangana',
      district: 'Rangareddy',
      occupation: 'Small Farmer',
      annual_income: 180000,
      social_category: 'OBC',
      land_holding_acres: 2.5,
      education_level: 'High School',
      is_student: false,
      is_farmer: true,
      is_business_owner: false,
      family_size: 4,
    },
    ai_summary: 'Based on your profile as a small landholder farmer in Telangana with an annual family income of ₹1.8 Lakhs, you qualify for multiple agricultural income support and credit programs as well as comprehensive cashless health insurance.',
  },
};
